services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  rediscommander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celerytutorial worker -l info

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py migrate django_celery_results && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      pgsql:
        condition: service_healthy
  pgsql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=securepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U djangouser -d djangodb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
